### ISSUE TITLE
Custom Text

### ISSUE THREAD

**Issue by Imiona** [MrMime71/PLHv2#2]
Hello

The Custom Text doesnt work, everytime i log out it gets reverted back to the default one.

Can you reproduce this?

Thx :)

**Comment by MrMime71** [comment]
I check it.

**Comment by MrMime71** [comment]
Fixed the issue..
Was a variable not being defined in .toc file.
Also changed the text that will be default if no text is made.
Have a nice weekend

**Comment by MrMime71** [comment]
to info.. as the .toc file is read when you start wow, you need to exit the game for changes to have effect
